---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deploy
  labels:
    name: argocd-deploy
    app: my-app

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: web-pod
      app: my-web
  template:
    metadata:
      name: httpd
      labels:
        name: web-pod
        app: my-web
    spec:
      containers:
      - name: httpd-container
        image: someshtarra/somesh:17
        ports:
        - containerPort: 8080
        
