---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deploy
  labels:
    name: argocd-deploy
    app: my-app

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: web-pod
      app: my-web
  template:
    metadata:
      labels:
        name: web-pod
        app: my-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - my-web
              topologyKey: kubernetes.io/hostname
      containers:
      - name: httpd-container
        image: someshtarra/projectimage:2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: '250m'
            memory: '64Mi'
          limits:
            cpu: '500m'
            memory: '200Mi'

        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        
        
