---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web-service
    app: my-web
spec:
  type: LoadBalancer
  selector:
    name: web-pod
    app: my-web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
